services:
  autoware:
    image: ghcr.io/autowarefoundation/autoware:universe
    volumes:
      - ../map:/root/autoware_map
    environment:
      - RUN_MODE=planning-simulator
      - MAP_PATH=/root/autoware_map
      - SCENARIO_SIMULATION=true
  
  scenario_simulator:
    image: ghcr.io/autowarefoundation/openadkit:scenario-simulator
    volumes:
      - ../map:/opt/autoware/share/kashiwanoha_map/map
      
  visualizer:
    image: ghcr.io/autowarefoundation/openadkit:visualizer
    ports:
      - 6080:6080
