services:
  autoware:
    image: ghcr.io/autowarefoundation/openadkit:autoware
    volumes:
      - autoware_map:/root/autoware_map
    environment:
      - RUN_MODE=planning-simulator
      - MAP_PATH=/root/autoware_map
      - SCENARIO_SIMULATION=true
    networks:
      autoware_net:
        ipv4_address: 172.20.0.2

  scenario_simulator:
    image: ghcr.io/autowarefoundation/openadkit:scenario-simulator
    volumes:
      - autoware_map:/opt/autoware/share/kashiwanoha_map/map
    networks:
      autoware_net:
        ipv4_address: 172.20.0.3

  visualizer:
    image: ghcr.io/autowarefoundation/openadkit:visualizer
    ports:
      - 6080:6080
    networks:
      autoware_net:
        ipv4_address: 172.20.0.4

volumes:
  autoware_map:

networks:
  autoware_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1