services:
  autoware:
    image: ghcr.io/autowarefoundation/openadkit:autoware
    volumes:
      - autoware_map:/root/autoware_map
      # Mount FastDDS profile
      - ./config/fastdds_profiles.xml:/root/fastdds_profiles.xml
    environment:
      - RUN_MODE=planning-simulator
      - MAP_PATH=/root/autoware_map
      - SENSOR_MODEL=sample_sensor_kit
      - VEHICLE_MODEL=sample_vehicle
      - SCENARIO_SIMULATION=true
      # Ask system to load FastDDS profile
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/fastdds_profiles.xml
    networks:
      autoware_net:
        ipv4_address: 172.20.0.2

  scenario_simulator:
    image: ghcr.io/autowarefoundation/openadkit:scenario-simulator
    volumes:
      - autoware_map:/opt/autoware/share/kashiwanoha_map/map
    networks:
      autoware_net:
        ipv4_address: 172.20.0.3

  visualizer:
    image: ghcr.io/autowarefoundation/openadkit:visualizer
    ports:
      - "6080:6080"
    volumes:
      # Mount FastDDS profile
      - ./config/fastdds_profiles.xml:/root/fastdds_profiles.xml
    environment:
      # Ask system to load FastDDS profile
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/fastdds_profiles.xml
    networks:
      visualizer_net:
        ipv4_address: 172.21.0.2

  autoware_zenoh_bridge:
    image: eclipse/zenoh-bridge-ros2dds:latest
    environment:
      - ROS_DISTRO=humble
    volumes:
      - ./config:/config
    command: -e tcp/172.22.0.3:7447 -c /config/zenoh-bridge-ros2dds.json5
    networks:
      autoware_net:
        ipv4_address: 172.20.0.5
      zenoh_net:
        ipv4_address: 172.22.0.2

  visualizer_zenoh_bridge:
    image: eclipse/zenoh-bridge-ros2dds:latest
    environment:
      - ROS_DISTRO=humble
    volumes:
      - ./config:/config
    command: -e tcp/172.22.0.2:7447 -c /config/zenoh-bridge-ros2dds.json5
    networks:
      visualizer_net:
        ipv4_address: 172.21.0.3
      zenoh_net:
        ipv4_address: 172.22.0.3

volumes:
  autoware_map:

networks:
  autoware_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
  visualizer_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
  zenoh_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1