services:
  autoware:
    image: ghcr.io/autowarefoundation/autoware:universe
    volumes:
      - autoware_map:/autoware_map
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    #   - RUN_MODE=planning-simulator
    #   - MAP_PATH=/root/autoware_map
    #   - SENSOR_MODEL=sample_sensor_kit
    #   - VEHICLE_MODEL=sample_vehicle
    #   - SCENARIO_SIMULATION=true
    networks:
      - autoware_net
    # entrypoint: >
    #   bash -c "echo 'Waiting for other services to start...' && sleep 16 && echo 'Starting service...'  && /entrypoint.sh"
    command: |
      ros2 launch autoware_launch planning_simulator.launch.xml
      map_path:=/autoware_map
      vehicle_model:=sample_vehicle
      sensor_model:=sample_sensor_kit
      scenario_simulation:=true
      rviz:=false
    depends_on:
      - autoware_zenoh_bridge
      - visualizer_zenoh_bridge

  scenario_simulator:
    image: ghcr.io/autowarefoundation/autoware-tools:scenario-simulator
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # volumes:
    #   - autoware_map:/opt/autoware/share/kashiwanoha_map/map
    networks:
      - autoware_net
    # entrypoint: >
    #   bash -c "echo 'Waiting for other services to start...' && sleep 8 && echo 'Starting service...'  && /entrypoint.sh"
    depends_on:
      - autoware_zenoh_bridge
      - visualizer_zenoh_bridge

  visualizer:
    image: ghcr.io/autowarefoundation/autoware-tools:visualizer
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    ports:
      - "6080:6080"
    networks:
      - visualizer_net
    # entrypoint: >
    #   bash -c "echo 'Waiting for other services to start...' && sleep 2 && echo 'Starting service...'  && /entrypoint.sh"
    depends_on:
      - autoware_zenoh_bridge
      - visualizer_zenoh_bridge

  autoware_zenoh_bridge:
    image: eclipse/zenoh-bridge-ros2dds:latest
    ports:
      - "7447:7447/tcp"
    environment:
      - ROS_DISTRO=humble
    volumes:
      - ./config:/config
    command: -c /config/zenoh-bridge-ros2dds.json5
    networks:
      - autoware_net
      - zenoh_net

  visualizer_zenoh_bridge:
    image: eclipse/zenoh-bridge-ros2dds:latest
    environment:
      - ROS_DISTRO=humble
    volumes:
      - ./config:/config
    command: -e tcp/autoware_zenoh_bridge:7447 -c /config/zenoh-bridge-ros2dds.json5
    networks:
      - visualizer_net
      - zenoh_net

volumes:
  autoware_map:

networks:
  autoware_net:
    driver: bridge
  visualizer_net:
    driver: bridge
  zenoh_net:
    driver: bridge